import path from "node:path";

import { parseDocument } from "yaml";

import {
  exists,
  listMarkdown,
  readTextIfExists,
  writeText,
} from "../filesystem.mjs";
import { splitFrontmatter } from "../render/frontmatter.mjs";
import { NAME } from "../version.mjs";

const GENERATED_MARKER = `Generated by ${NAME}`;
const DUPLICATE_THRESHOLD = 0.8;

const MANIFEST_TEMPLATE = `version: 1

targets:
  claude:
    enabled: true

  codex:
    enabled: true

agents: []

rules: []

commands: []
`;

/** Instruction files split into rules; agent and command files copied one to one. */
const DOCUMENTS = [
  "CLAUDE.md",
  "AGENTS.md",
  ".github/copilot-instructions.md",
  ".cursorrules",
];

const DIRECTORIES = [
  { from: ".claude/agents", kind: "agents" },
  { from: ".claude/commands", kind: "commands" },
  { from: ".cursor/rules", kind: "rules" },
];

/**
 * Adoption is deliberately mechanical: it splits on headings and never rewrites
 * content. Merging near-duplicates is a human judgment, so the plan only makes
 * the drift visible in one place for the first time.
 */
export async function planAdoption(root) {
  const projectRoot = path.resolve(root);
  const owned = await ownedPaths(projectRoot);
  const imports = [];
  const skipped = [];

  const isGenerated = (relative, contents) =>
    owned.has(relative) || contents.includes(GENERATED_MARKER);

  for (const relative of DOCUMENTS) {
    const contents = await readTextIfExists(path.join(projectRoot, relative));

    if (contents === undefined) {
      continue;
    }

    if (isGenerated(relative, contents)) {
      skipped.push({ source: relative, reason: "generated by this compiler" });
      continue;
    }

    imports.push(...splitDocument(relative, contents));
  }

  for (const { from, kind } of DIRECTORIES) {
    const directory = path.join(projectRoot, from);

    for (const name of await listSources(directory)) {
      const relative = path.posix.join(from, name);
      const contents = await readTextIfExists(path.join(directory, name));

      if (contents === undefined || isGenerated(relative, contents)) {
        skipped.push({ source: relative, reason: "generated by this compiler" });
        continue;
      }

      imports.push({
        kind,
        id: slug(name.replace(/\.(md|mdc)$/, "")),
        source: relative,
        body: contents,
      });
    }
  }

  const writes = [];
  const taken = new Set();

  for (const item of await resolveTargets(projectRoot, imports, taken)) {
    if (item.status === "write") {
      writes.push(item);
    } else {
      skipped.push({ source: item.source, reason: item.reason });
    }
  }

  return {
    writes,
    skipped,
    duplicates: findDuplicates(writes),
    manifest: await planManifest(projectRoot, writes),
  };
}

export async function adopt(root, options = {}) {
  const plan = await planAdoption(root);

  if (!options.write) {
    return { ...plan, written: false };
  }

  for (const item of plan.writes) {
    await writeText(path.join(root, item.path), item.contents);
  }

  if (plan.manifest.changed) {
    await writeText(path.join(root, plan.manifest.path), plan.manifest.contents);
  }

  return { ...plan, written: true };
}

function splitDocument(relative, contents) {
  const { body } = splitFrontmatter(contents);
  const lines = body.split("\n");
  const sections = [];
  let current = { heading: undefined, lines: [] };

  for (const line of lines) {
    const heading = /^##\s+(.+?)\s*$/.exec(line);

    if (heading) {
      sections.push(current);
      current = { heading: heading[1], lines: [] };
      continue;
    }

    current.lines.push(line);
  }

  sections.push(current);

  const base = slug(path.basename(relative).replace(/\.md$/, ""));

  return sections
    .filter((section) => section.lines.join("\n").trim() || section.heading)
    .map((section) => ({
      kind: "rules",
      id: section.heading ? slug(section.heading) : `${base}-preamble`,
      source: relative,
      heading: section.heading,
      body: section.lines.join("\n").trim() + "\n",
    }));
}

async function resolveTargets(root, imports, taken) {
  const resolved = [];

  for (const item of imports) {
    const contents = withProvenance(item);
    let id = item.id;
    let attempt = 1;

    // eslint-disable-next-line no-constant-condition
    while (true) {
      const relative = path.posix.join(".ai", item.kind, `${id}.md`);

      if (taken.has(relative)) {
        attempt += 1;
        id = `${item.id}-${attempt}`;
        continue;
      }

      const existing = await readTextIfExists(path.join(root, relative));

      if (existing === undefined) {
        taken.add(relative);
        resolved.push({ ...item, id, path: relative, contents, status: "write" });
        break;
      }

      if (existing === contents) {
        resolved.push({ ...item, id, path: relative, status: "skip", reason: "already adopted" });
        break;
      }

      attempt += 1;
      id = `${item.id}-${attempt}`;
    }
  }

  return resolved;
}

function withProvenance(item) {
  const lines = [`adopted-from: ${item.source}`];

  if (item.heading) {
    lines.push(`adopted-section: ${JSON.stringify(item.heading)}`);
  }

  const { body } = splitFrontmatter(item.body);

  return `---\n${lines.join("\n")}\n---\n\n${body.trim()}\n`;
}

function findDuplicates(writes) {
  const duplicates = [];

  for (let left = 0; left < writes.length; left += 1) {
    for (let right = left + 1; right < writes.length; right += 1) {
      if (writes[left].kind !== writes[right].kind) {
        continue;
      }

      const similarity = jaccard(tokens(writes[left].body), tokens(writes[right].body));

      if (similarity >= DUPLICATE_THRESHOLD) {
        duplicates.push({
          paths: [writes[left].path, writes[right].path],
          sources: [writes[left].source, writes[right].source],
          similarity: Math.round(similarity * 100),
        });
      }
    }
  }

  return duplicates;
}

function tokens(text) {
  return new Set(text.toLowerCase().match(/[a-z0-9]+/g) ?? []);
}

function jaccard(left, right) {
  if (!left.size && !right.size) {
    return 1;
  }

  let shared = 0;

  for (const item of left) {
    if (right.has(item)) {
      shared += 1;
    }
  }

  return shared / (left.size + right.size - shared);
}

/**
 * Names are appended to the existing manifest with the YAML document API, so a
 * user's comments and formatting survive adoption.
 */
async function planManifest(root, writes) {
  const relative = path.posix.join(".ai", "manifest.yaml");
  const file = path.join(root, relative);
  const existing = await readTextIfExists(file);
  const document = parseDocument(existing ?? MANIFEST_TEMPLATE);
  const added = {};
  let changed = existing === undefined;

  for (const kind of ["agents", "rules", "commands"]) {
    const ids = writes.filter((item) => item.kind === kind).map((item) => item.id);

    if (!ids.length) {
      continue;
    }

    const current = document.get(kind);
    const listed = new Set((current?.toJSON?.() ?? current ?? []).map(String));
    const fresh = ids.filter((id) => !listed.has(id));

    if (!fresh.length) {
      continue;
    }

    if (!current || typeof current.add !== "function") {
      const node = document.createNode([...listed, ...fresh]);

      node.flow = false;
      document.set(kind, node);
    } else {
      for (const id of fresh) {
        current.add(id);
      }

      // An empty `rules: []` parses as a flow sequence; keep the grown list
      // readable as a block list instead.
      current.flow = false;
    }

    added[kind] = fresh;
    changed = true;
  }

  return { path: relative, contents: document.toString(), added, changed, created: existing === undefined };
}

/**
 * Files a previous sync generated are output, not source. Agent and command
 * files are verbatim copies with no banner to recognize, so the ownership
 * records are the only reliable way to tell them apart.
 */
async function ownedPaths(root) {
  const directory = path.join(root, ".ai", "state", "targets");
  const owned = new Set();
  let entries;

  try {
    const { readdir } = await import("node:fs/promises");

    entries = (await readdir(directory)).filter((name) => name.endsWith(".json"));
  } catch {
    return owned;
  }

  for (const name of entries) {
    const contents = await readTextIfExists(path.join(directory, name));

    try {
      for (const item of JSON.parse(contents).paths ?? []) {
        owned.add(item);
      }
    } catch {
      continue;
    }
  }

  return owned;
}

async function listSources(directory) {
  if (!(await exists(directory))) {
    return [];
  }

  const markdown = await listMarkdown(directory);
  const { readdir } = await import("node:fs/promises");
  const all = (await readdir(directory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(".mdc"))
    .map((entry) => entry.name);

  return [...markdown, ...all].sort((left, right) => left.localeCompare(right));
}

function slug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "untitled";
}
