const NOTE_PATTERN = /^[ \t]*<!--\s*aie:note[\s\S]*?-->[ \t]*\r?\n?/gm;
const FRONTMATTER_PATTERN = /^---\r?\n[\s\S]*?\r?\n---[ \t]*(\r?\n|$)/;

export function banner(target, generator) {
  return [
    "<!--",
    "",
    `Generated by ${generator} (${target})`,
    "",
    "DO NOT EDIT. Edit .ai/ and run: aie sync",
    "",
    "-->",
    "",
    "",
  ].join("\n");
}

/**
 * Renders one Markdown section per source entry. Shared by every adapter so
 * ordering, headings, and separators cannot drift between runtimes.
 */
export function renderSections(entries, label) {
  return entries
    .map((entry) => `## ${label}: ${entry.id}\n\n${stripFrontmatter(entry.content).trim()}`)
    .join("\n\n---\n\n");
}

export function stripFrontmatter(content) {
  return content.replace(FRONTMATTER_PATTERN, "");
}

export function applyTemplate(template, values) {
  return Object.entries(values).reduce(
    (result, [name, value]) => result.split(`{{${name}}}`).join(value),
    template
  );
}

export function missingPlaceholders(template, required) {
  return required.filter((name) => !template.includes(`{{${name}}}`));
}

/**
 * Produces a stable document from a rendered template: authoring notes are
 * removed, blank runs collapse, and separators left dangling by an empty
 * section disappear instead of trailing a `---` into the output.
 */
export function normalizeDocument(text) {
  const lines = text
    .replace(/\r\n/g, "\n")
    .replace(NOTE_PATTERN, "")
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""));

  const collapsed = [];

  for (const line of lines) {
    if (line === "" && collapsed.at(-1) === "") {
      continue;
    }

    collapsed.push(line);
  }

  const meaningful = collapsed.filter((line, index) => {
    if (!isSeparator(line)) {
      return true;
    }

    return hasContentBefore(collapsed, index) && hasContentAfter(collapsed, index);
  });

  while (meaningful.length && meaningful[0] === "") {
    meaningful.shift();
  }

  while (meaningful.length && meaningful.at(-1) === "") {
    meaningful.pop();
  }

  return meaningful.length ? `${meaningful.join("\n")}\n` : "";
}

function isSeparator(line) {
  return /^-{3,}$/.test(line.trim());
}

function hasContentBefore(lines, index) {
  for (let cursor = index - 1; cursor >= 0; cursor -= 1) {
    if (lines[cursor] === "") {
      continue;
    }

    return !isSeparator(lines[cursor]);
  }

  return false;
}

function hasContentAfter(lines, index) {
  for (let cursor = index + 1; cursor < lines.length; cursor += 1) {
    if (lines[cursor] === "") {
      continue;
    }

    return true;
  }

  return false;
}
