import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import {
  assertManagedPath,
  createAdapterRegistry,
  validateAdapterRegistry,
} from "../registry.mjs";
import { DiagnosticError, createDiagnostics, fail } from "../diagnostics.mjs";
import {
  fileMode,
  pruneEmptyDirectories,
  readTextIfExists,
  removeFile,
  writeText,
} from "../filesystem.mjs";
import { loadWorkspace } from "../manifest/workspace.mjs";
import {
  fromPosix,
  ownershipFile,
  readOwnership,
  serializeOwnership,
  toPosix,
  writeOwnership,
} from "../state/ownership.mjs";
import { NAME } from "../version.mjs";

const BUILT_IN_ADAPTERS = new URL("../adapters/", import.meta.url);
const GENERATED_MARKER = `Generated by ${NAME}`;

/** The workspace materializes its own generated sources before adapters run. */
const WORKSPACE_TARGET = "workspace";

export async function plan(options = {}) {
  const { manifest, registry, diagnostics } = await prepare(options);
  const enabled = registry.filter((adapter) => isEnabled(manifest, adapter));
  const claimed = new Map();
  const targets = [];

  if (manifest.generated.length) {
    targets.push({
      id: WORKSPACE_TARGET,
      files: normalizeFiles(
        { id: WORKSPACE_TARGET },
        manifest.generated,
        claimed,
        { allowGenerated: true }
      ),
      remove: [],
    });
  }

  for (const adapter of enabled) {
    const context = await renderContext(adapter, manifest);
    const result = await adapter.render(manifest, context);

    if (!result || !Array.isArray(result.files)) {
      fail(
        `Adapter "${adapter.id}" must return { files: [{ path, contents }] }. ` +
        "Adapters no longer write to disk; the compiler owns every write."
      );
    }

    for (const diagnostic of result.diagnostics ?? []) {
      diagnostics.push({ target: adapter.id, ...diagnostic });
    }

    targets.push({
      id: adapter.id,
      files: normalizeFiles(adapter, result.files, claimed),
      remove: normalizeRemovals(adapter, result.remove ?? []),
    });
  }

  diagnostics.throwIfFailed({ strict: options.strict });

  return { manifest, registry, diagnostics, targets };
}

export async function inspect(options = {}) {
  const planned = await plan(options);
  const { manifest, diagnostics } = planned;
  const root = manifest.root;
  const collisions = [];
  const targets = [];

  for (const target of planned.targets) {
    const ownership = await readOwnership(root, target.id);
    const owned = new Set(ownership.paths);
    const plannedPaths = target.files.map((file) => file.path);
    const plannedSet = new Set(plannedPaths);
    const artifacts = [];

    for (const file of target.files) {
      const absolute = path.join(root, fromPosix(file.path));
      const existing = await readTextIfExists(absolute);
      let action;

      if (existing === undefined) {
        action = "created";
      } else if (existing === file.contents && await modeMatches(absolute, file.mode)) {
        action = "unchanged";
      } else if (file.kind === "merge" || owned.has(file.path) || options.force) {
        // A merged file is shared with the user by design: the adapter has
        // already preserved everything it does not own, so rewriting it is safe.
        action = "updated";
      } else {
        action = "collision";
        collisions.push({ target: target.id, path: file.path });
      }

      artifacts.push({ ...file, absolute, kind: file.kind ?? "artifact", action });
    }

    const stale = ownership.paths.filter((item) => !plannedSet.has(item));
    const legacy = await resolveLegacyRemovals(target, root, plannedSet, diagnostics);
    const merged = collectMerged(target.files);

    artifacts.push(await stateArtifact(root, target.id, plannedPaths, merged));

    targets.push({
      id: target.id,
      files: artifacts.filter((artifact) => artifact.action !== "unchanged").length,
      artifacts,
      paths: plannedPaths,
      merged,
      removed: [...stale, ...legacy],
    });
  }

  return { ...planned, targets, collisions, changed: hasChanges(targets) };
}

export async function compile(options = {}) {
  const inspection = await inspect(options);
  const root = inspection.manifest.root;

  if (inspection.collisions.length && !options.force) {
    throw collisionError(inspection.collisions);
  }

  for (const target of inspection.targets) {
    for (const artifact of target.artifacts) {
      if (artifact.action === "unchanged" || artifact.kind === "state") {
        continue;
      }

      await writeText(artifact.absolute, artifact.contents, artifact.mode);
    }

    for (const relative of target.removed) {
      const absolute = path.join(root, fromPosix(relative));

      await removeFile(absolute);
      await pruneEmptyDirectories(absolute, root);
    }

    await writeOwnership(root, target.id, target.paths, NAME, target.merged);
  }

  return inspection;
}

export async function validate(options = {}) {
  return plan(options);
}

async function prepare(options) {
  const diagnostics = options.diagnostics ?? createDiagnostics();
  const manifest = options.manifest
    ?? await loadWorkspace(options.root ?? process.cwd(), { diagnostics });
  const registry = options.registry ?? await createAdapterRegistry(
    options.adapterDirectory ?? fileURLToPath(BUILT_IN_ADAPTERS)
  );

  validateAdapterRegistry(registry);
  validateEnabledTargets(manifest, registry);

  return { manifest, registry, diagnostics };
}

/**
 * Adapters never touch the filesystem, so the compiler pre-reads the files an
 * adapter declared it merges into, along with the entries it owned last time.
 */
async function renderContext(adapter, manifest) {
  const existing = {};

  for (const artifact of adapter.surface?.artifacts ?? []) {
    if (artifact.merge) {
      existing[artifact.path] = await readTextIfExists(
        path.join(manifest.root, fromPosix(artifact.path))
      );
    }
  }

  const ownership = await readOwnership(manifest.root, adapter.id);

  return { existing, owned: { paths: ownership.paths, merged: ownership.merged } };
}

function validateEnabledTargets(manifest, registry) {
  const available = new Set(registry.map((adapter) => adapter.id));

  for (const [id, target] of Object.entries(manifest.targets)) {
    if (target.enabled !== false && !available.has(id)) {
      fail(`No adapter is installed for enabled target "${id}"`);
    }
  }
}

function isEnabled(manifest, adapter) {
  const target = manifest.targets[adapter.id];

  return target && target.enabled !== false;
}

function normalizeFiles(adapter, files, claimed, options = {}) {
  return files.map((file) => {
    const subject = `Adapter "${adapter.id}"`;
    const normalized = toPosix(assertManagedPath(file.path, subject, options));

    if (typeof file.contents !== "string") {
      fail(`${subject} must provide string contents for "${normalized}"`);
    }

    const owner = claimed.get(normalized);

    if (owner === adapter.id) {
      fail(`${subject} generates "${normalized}" twice`);
    }

    if (owner) {
      fail(
        `Targets "${owner}" and "${adapter.id}" both generate "${normalized}". ` +
        "Give one of them a different output path."
      );
    }

    claimed.set(normalized, adapter.id);

    return {
      path: normalized,
      contents: file.contents,
      ...(file.mode === undefined ? {} : { mode: file.mode }),
      ...(file.kind === undefined ? {} : { kind: file.kind }),
      ...(file.owns === undefined ? {} : { owns: file.owns }),
    };
  });
}

function normalizeRemovals(adapter, removals) {
  return removals.map((entry) => ({
    path: toPosix(assertManagedPath(entry.path, `Adapter "${adapter.id}" removal`)),
    proof: entry.proof ?? { kind: "banner" },
  }));
}

function collectMerged(files) {
  return Object.fromEntries(
    files.filter((file) => file.kind === "merge" && file.owns).map((file) => [file.path, file.owns])
  );
}

async function modeMatches(absolute, mode) {
  if (mode === undefined) {
    return true;
  }

  return await fileMode(absolute) === mode;
}

/**
 * A removal outside the ownership record is only performed when the file proves
 * the compiler wrote it: it carries the generated banner, or its bytes still
 * match the source it was copied from.
 */
async function resolveLegacyRemovals(target, root, plannedSet, diagnostics) {
  const removable = [];

  for (const entry of target.remove) {
    if (plannedSet.has(entry.path)) {
      continue;
    }

    const existing = await readTextIfExists(path.join(root, fromPosix(entry.path)));

    if (existing === undefined) {
      continue;
    }

    if (isProven(entry.proof, existing)) {
      removable.push(entry.path);
      continue;
    }

    diagnostics.warning(
      "legacy-artifact-preserved",
      `"${entry.path}" is no longer generated but was modified after it was written, so it was left in place. Delete it manually once you no longer need it.`,
      { file: entry.path, target: target.id }
    );
  }

  return removable;
}

function isProven(proof, existing) {
  if (proof.kind === "equals") {
    return existing === proof.contents;
  }

  return existing.includes(GENERATED_MARKER);
}

async function stateArtifact(root, id, plannedPaths, merged) {
  const contents = serializeOwnership(id, plannedPaths, NAME, merged);
  const absolute = ownershipFile(root, id);
  const existing = await readTextIfExists(absolute);

  return {
    path: toPosix(path.relative(root, absolute)),
    contents,
    absolute,
    kind: "state",
    action: existing === undefined
      ? "created"
      : existing === contents ? "unchanged" : "updated",
  };
}

function hasChanges(targets) {
  return targets.some((target) =>
    target.removed.length
    || target.artifacts.some((artifact) => artifact.action !== "unchanged"));
}

function collisionError(collisions) {
  const list = collisions.map((item) => `  ${item.path} (${item.target})`).join("\n");

  return new DiagnosticError(
    `Refusing to overwrite files this workspace does not own:\n\n${list}\n\n` +
    "Move them aside, or run with --force to overwrite them and take ownership.",
    collisions.map((item) => ({
      severity: "error",
      code: "output-collision",
      message: `"${item.path}" already exists and was not generated by this workspace`,
      file: item.path,
      target: item.target,
    }))
  );
}
