import path from "node:path";

import {
  removeDirectory,
  readText,
  writeText,
} from "../filesystem.mjs";

export const id = "codex";

export async function render(manifest) {
  const template = await readText(
    path.join(manifest.files.templates, "codex-agents.md")
  );
  const output = template
    .replace("{{RULES}}", await renderSections(manifest.rules, "Rule", manifest.resolve.rule))
    .replace("{{AGENTS}}", await renderSections(manifest.agents, "Agent", manifest.resolve.agent));
  const destination = path.join(manifest.resolve.output(id), "AGENTS.md");

  await removeDirectory(manifest.resolve.output(id));
  await writeText(destination, banner(id) + output);

  return { files: 1 };
}

async function renderSections(names, label, resolve) {
  const sections = await Promise.all(names.map(async (name) => [
    `## ${label}: ${name}`,
    "",
    (await readText(resolve(name))).trim(),
  ].join("\n")));

  return sections.join("\n\n---\n\n");
}

function banner(target) {
  return [
    "<!--",
    "",
    `Generated by @akin/ai-engineering (${target})`,
    "",
    "DO NOT EDIT.",
    "",
    "-->",
    "",
  ].join("\n");
}
